window.onload = function() {
  const texts = [
            
      	"how are you? actually nvm idrc",
        "todo: add funny comment",
        "As seen on TV!",
        "Awesome!",
        "May contain nuts!",
        "One of a kind!",
        "Not on steam!",
        "Oh man!",
        "Pixels!",
        "Now with difficulty!",
        "Enhanced!",
        "90% bug free!",
        "Absolutely no memes!",
        "Ask your doctor!",
        "GOTY!",
        "Yes, sir!",
        "Try it!",
        "Call your mother!",
        "Ultimate edition!",
        "Freaky!",
        "Water proof!",
        "Uninflammable!",
        "Whoa, dude!",
        "All inclusive!",
        "Tell your friends!",
        "Full of stars!",
        "Scientific!",
        "Not as cool as Draco!",
        "Never dig down!",
        "Take frequent breaks!",
        "Not linear!",
        "Seecret Friday update!",
        "Reference implementation!",
        "Peter Griffin!",
        "Do not distribute!",
        "Cogito ergo sum!",
        "4815162342 lines of code!",
        "Supercalifragilisticexpialidocious!",
        "Woo, facepunch!",
      	"Hotter than the sun!",
      	"Almost as hot as you",
       	"Fuck iPhones",
      	"Don't stop me now!",
      	"Tip your waiter!",
      	"Pinacolada!",
        "Very fun!",
        "12345 is a bad password!",
	      "password is a bad password!",
      	"Nobita",
        "...in a pineapple under the sea!",
        "...!",
        "Bees, bees, bees, bees!",
        "Haha, LOL!",
        "Finally with ladders!",
        "21st night of sep",
        "Wrapped in a mystery!",
        "Welcome to your Doom!",
        "Stay a while, stay forever!",
        "Stay a while and listen!",
        "Treatment for your rash!",
        "Information wants to be free!",
        "\"Almost never\" means shit",
        "Lots of truthiness!",
        "The creeper is a spy!",
        "Turing complete!",
        "It's groundbreaking!",
        "Let our battle's begin!",
        "The sky is the limit!",
      	"What's the chance of this?",
        "Bread is pain!",
        "Read more books!",
        "This is my true form!",
        "Made by Jeb!",
        "Has an ending!",
        "Finally complete!",
        "Feature packed!",
        "Stop, hammertime!",
        "Does barrel rolls!",
        "Meeting expectations!",
        "PC gaming since 1873!",
        "Déjà vu!",
        "Déjà vu!",
	      "put on wax take off wax",
	      "Rocky dad!"
        "Got your nose!",
        "Haley loves Elan!",
        "Afraid of the big, black bat!",
        "See you next Friday or so!",
        "Every road leads to Rome!",
        "Who put it there?",
        "You can't explain that!",
        "if not ok then return end",
        "Plz reply to my tweet!",
        "Woah.",
        "One day, I will be quoted!",
        "Now with additional stuff!",
        "Extra things!",
        "Strange, but not a stranger!",
        "don't be reasonable online!",
        "Any computer is a laptop",
      	"Any laptop is a computer",
        "Do it all, everything!",
        "doot doot",
        "Falling with style!",
        "Rule #1: it's never my fault",
        "not to be played while driving",
        "You're going too fast!",
        "All rumors are true!",
        "I need more context.",
        "Ahhhhhh!",
        "Don't worry, be happy!",
        "Water bottle!",
        "What's the question?",
        "Plant a tree!",
        "Look mum, I'm famous!",
        "It came from space.",
        "Wash your hands!",
        "Soap and water!",
        "Support local businesses!",
        "Stay home and play games!",
        "Stay safe!",
        "Stay strong!",    
        "Don’t touch your face!",
        "Support elderly relatives!",
      	"Help your friends!",
        "Prepare, but don’t hoard!",
        "Aww man!",
        "Contains simulated goats!",
        "Home-made!",
        "c4t on ,y keyb.ard!~",
	      "My jee key is broken, jamers",
        "Get to the coppah!",
        "Board game version available!",
        "Who let the frogs out?",
        "Nooooooooooooo!",
        "Flower forest TM perfume",
        "Hat Fridays!",
        "Technoblade never dies!",
        "You are valid!",
        "I'm glad you're here!",
        "You are welcome here!",
        "This sand is sus",
        "Sniff sniff...",
        "Place hanging sign here",
        "Stay alive!"
        "Welcome Dude!",
        "Also try Terraria!",
        "Hello Mr. stalker",
        "bro clicked the link",
        "Lorem ipsum dolor",
        "good night",
        "blud shouldn't be here",
        "Curious, are we?",
        "Wrong website dummy",
        "I've been waiting for you",
        "Unexpected stop, huh?",
        "Is this a dead end?",
        "This is not a coincidence",
        "Pizza, pasta, mamma mia",
        "Ciao!",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "i might (am) be stupid"
        ];

        const randomIndex = Math.floor(Math.random() * texts.length);
        document.getElementById('random-texts').innerText = texts[randomIndex];
};
